---
apiVersion: v1
kind: List
metadata:
  name: istio-config-list
  namespace: logistics
items:
  - apiVersion: networking.istio.io/v1alpha3
    kind: Gateway
    metadata:
      name: microservices
      namespace: logistics
    spec:
      selector:
        istio: ingressgateway
      servers:
        - hosts:
            - "*"
          port:
            name: http
            number: 80
            protocol: HTTP
  - apiVersion: networking.istio.io/v1alpha3
    kind: VirtualService
    metadata:
      name: microservices
      namespace: logistics
    spec:
      gateways:
        - microservices
      hosts:
        - "*"
      http:
        - match:
            - uri:
                prefix: /
          route:
            - destination:
                host: logistics-svc
                port:
                  number: 8080
