apiVersion: v1
kind: Namespace
metadata:
  name: "logistics"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: logistics-quotas
  namespace: "logistics"
  labels:
    razee/watch-resource: "true"
spec:
  hard:
    cpu: "1000"
    memory: 200Gi
    pods: "100"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logistics-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  name: logistics-dev
  namespace: "logistics"